<?php

defined('TYPO3_MODE') || die();

(static function (): void {
    $extensionKey = 'eset_translator';

    // Page tree context menu: the "ESET" submenu.
    // v10.4 reads providers from BE/ContextMenu/ItemProviders (see
    // \TYPO3\CMS\Backend\ContextMenu\ContextMenu::getItemProviders()).
    $GLOBALS['TYPO3_CONF_VARS']['BE']['ContextMenu']['ItemProviders'][1710000200]
        = \ESET\Translator\ContextMenu\PageTreeItemProvider::class;

    // Page module doc header buttons (v10.4 has no ModifyButtonBarEvent).
    // The hook key is the legacy short string, not ButtonBar::class (see
    // \TYPO3\CMS\Backend\Template\Components\ButtonBar::getButtons()).
    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['Backend\Template\Components\ButtonBar']['getButtonsHook'][1710000300]
        = \ESET\Translator\EventListener\PageModuleButtonListener::class . '->getButtons';

    // Icons.
    $iconRegistry = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
        \TYPO3\CMS\Core\Imaging\IconRegistry::class
    );
    $icons = [
        'eset-translator-module' => 'module.svg',
        'eset-translator-translate' => 'translate.svg',
        'eset-translator-exchange' => 'exchange.svg',
        'eset-translator-job' => 'job.svg',
    ];
    foreach ($icons as $identifier => $file) {
        $iconRegistry->registerIcon(
            $identifier,
            \TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider::class,
            ['source' => 'EXT:' . $extensionKey . '/Resources/Public/Icons/' . $file]
        );
    }

    // RequireJS paths (TYPO3/CMS/EsetTranslator/*) are auto-generated by the
    // core from Resources/Public/JavaScript, no registration needed.
    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_pagerenderer.php']['render-preProcess'][$extensionKey]
        = \ESET\Translator\Hooks\PageRendererHook::class . '->addInlineLanguageLabels';

    // Default page TSconfig (context menu is not disabled, module label, ...).
    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig(
        '@import "EXT:' . $extensionKey . '/Configuration/TsConfig/Page/All.tsconfig"'
    );
    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addUserTSConfig(
        '@import "EXT:' . $extensionKey . '/Configuration/TsConfig/User/All.tsconfig"'
    );
})();
